name       : dvd_rw-tools
version    : 7.1
release    : 4
source     :
    - http://fy.chalmers.se/~appro/linux/DVD+RW/tools/dvd+rw-tools-7.1.tar.gz : f8d60f822e914128bcbc5f64fbe3ed131cbff9045dca7e12c5b77b26edde72ca
license    : GPL-2.0
summary    : DVD Manipulation tools
component  : library
description: |
    DVD Manipulation tools
rundeps    :
    - libisoburn
setup      : |
    %apply_patches
    #%patch -p1 < $pkgfiles/libisoburn.patch
build      : |
    %make all rpl8 btcflash
install    : |
    %make_install prefix=$installdir/usr
